#!/usr/bin/env bash
# Carbon-Aware Dispatcher — Quick Setup
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/peterklingelhofer/carbon-aware-dispatcher/main/setup.sh | bash
#
# Or with options:
#   curl -fsSL ... | bash -s -- --threshold 200 --zones "auto:green"
#
# This creates a GitHub Actions workflow file in your repo that runs
# your CI only when the energy grid is clean. No API keys needed.

set -euo pipefail

# Defaults
THRESHOLD="250"
ZONES=""
STRATEGY="check"
CRON="0 * * * *"
WORKFLOW_NAME="carbon-aware-build"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --threshold|-t) THRESHOLD="$2"; shift 2 ;;
        --zones|-z) ZONES="$2"; shift 2 ;;
        --strategy|-s) STRATEGY="$2"; shift 2 ;;
        --cron|-c) CRON="$2"; shift 2 ;;
        --name|-n) WORKFLOW_NAME="$2"; shift 2 ;;
        --help|-h)
            echo "Usage: setup.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --threshold, -t  Max carbon intensity in gCO2eq/kWh (default: 250)"
            echo "  --zones, -z      Grid zones or preset (default: auto-detect)"
            echo "                   Presets: auto:detect, auto:green, auto:cleanest,"
            echo "                   auto:escape-coal, auto:escape-coal:IN"
            echo "  --strategy, -s   check (default) or queue"
            echo "  --cron, -c       Cron schedule (default: '0 * * * *' = hourly)"
            echo "  --name, -n       Workflow filename (default: carbon-aware-build)"
            echo ""
            echo "Examples:"
            echo "  setup.sh                              # Zero-config, auto-detect region"
            echo "  setup.sh --threshold 150              # Strict threshold"
            echo "  setup.sh --zones 'auto:escape-coal'   # Route away from coal grids"
            echo "  setup.sh --strategy queue --cron '0 6 * * *'  # Find optimal daily window"
            exit 0
            ;;
        *) echo "Unknown option: $1. Use --help for usage."; exit 1 ;;
    esac
done

# Check we're in a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "Error: Not in a git repository. Run this from your project root."
    exit 1
fi

# Create workflow directory
WORKFLOW_DIR=".github/workflows"
mkdir -p "$WORKFLOW_DIR"

WORKFLOW_FILE="$WORKFLOW_DIR/${WORKFLOW_NAME}.yml"

if [[ -f "$WORKFLOW_FILE" ]]; then
    echo "Workflow already exists at $WORKFLOW_FILE"
    read -rp "Overwrite? [y/N] " confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# Build the workflow file
cat > "$WORKFLOW_FILE" << WORKFLOW_EOF
# Carbon-Aware Build — runs CI only on clean energy
# Generated by: carbon-aware-dispatcher setup.sh
# Docs: https://github.com/peterklingelhofer/carbon-aware-dispatcher

name: Carbon-Aware Build
on:
  schedule:
    - cron: '${CRON}'
  workflow_dispatch:

jobs:
  green-check:
    runs-on: ubuntu-latest
    outputs:
      clean: \${{ steps.carbon.outputs.grid_clean }}
      zone: \${{ steps.carbon.outputs.grid_zone }}
      intensity: \${{ steps.carbon.outputs.carbon_intensity }}
    steps:
      - uses: peterklingelhofer/carbon-aware-dispatcher@v1
        id: carbon
WORKFLOW_EOF

# Add optional inputs
if [[ -n "$ZONES" || "$THRESHOLD" != "250" || "$STRATEGY" != "check" ]]; then
    echo "        with:" >> "$WORKFLOW_FILE"
    [[ -n "$ZONES" ]] && echo "          grid_zones: '${ZONES}'" >> "$WORKFLOW_FILE"
    [[ "$THRESHOLD" != "250" ]] && echo "          max_carbon_intensity: '${THRESHOLD}'" >> "$WORKFLOW_FILE"
    [[ "$STRATEGY" != "check" ]] && echo "          strategy: '${STRATEGY}'" >> "$WORKFLOW_FILE"
fi

cat >> "$WORKFLOW_FILE" << 'WORKFLOW_EOF'

  build:
    needs: green-check
    if: needs.green-check.outputs.clean == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Running on clean energy in ${{ needs.green-check.outputs.zone }}!"
          echo "Carbon intensity: ${{ needs.green-check.outputs.intensity }} gCO2eq/kWh"
          # Add your build/test/deploy commands here
WORKFLOW_EOF

echo ""
echo "Created $WORKFLOW_FILE"
echo ""
echo "Next steps:"
echo "  1. Add your build commands to the 'build' job"
echo "  2. Commit and push:"
echo "     git add $WORKFLOW_FILE && git commit -m 'Add carbon-aware CI' && git push"
echo ""
echo "Your CI will now only run when the energy grid is clean!"
echo "No API keys needed — works out of the box for US, UK, EU, Australia, India, Brazil."
echo ""
echo "Options: https://github.com/peterklingelhofer/carbon-aware-dispatcher#inputs"
