blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/peterklingelhofer/carbon-aware-dispatcher/security/advisories/new
    about: Please report security issues privately through a security advisory.
