"""Turn docs/CITATIONS.csl.json into a type-checked citekey set and a readable bibliography.

Two outputs from one source of truth:

  citations_generated.py  a `CitationId` Literal of every valid citekey. Code that
                          attaches a citekey to a constant is annotated with it, so
                          `mypy` rejects a citekey that is not in the corpus. That
                          is this project's version of the compile error the
                          reference implementation gets from TypeScript.
  docs/CITATIONS.md       the human rendering. The hand-written preamble and the
                          trailing gaps ledger are preserved verbatim; everything
                          between them, including the counts, is regenerated, so
                          the prose and the corpus cannot drift apart.

Duplicate or malformed citekeys, and entries in no known group, fail the run.
"""

import argparse
import json
import os
import re
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "docs", "CITATIONS.csl.json")
TYPES = os.path.join(ROOT, "citations_generated.py")
MARKDOWN = os.path.join(ROOT, "docs", "CITATIONS.md")

CITEKEY = re.compile(r"^[a-z0-9][a-z0-9-]*$")

# Section order in the rendered bibliography.
GROUPS = [
    ("emission-factors", "Emission factors"),
    ("methodology", "Methodology"),
    ("grid-data", "Grid data sources"),
    ("compute-energy", "Compute energy"),
    ("equivalences", "Equivalence factors"),
    ("standards", "Standards & policy"),
]

VERIFICATION_LABEL = {
    "crossref-verified": "Crossref-verified",
    "datacite-verified": "DataCite-verified",
    "url-verified": "URL-verified",
    "primary-read": "PRIMARY TEXT READ",
    "unverified": "UNVERIFIED",
}

LEDGER_HEADING = "## Unsourced and weakly-sourced claims"


def load():
    with open(SOURCE) as fh:
        entries = json.load(fh)
    if not isinstance(entries, list):
        raise SystemExit("CITATIONS.csl.json must be a JSON array")
    return entries


def validate(entries):
    """Reject duplicates, malformed keys and unknown groups. Returns sorted ids."""
    ids = [entry.get("id", "") for entry in entries]
    duplicates = sorted({key for key, n in Counter(ids).items() if n > 1})
    if duplicates:
        raise SystemExit(f"duplicate citekeys: {', '.join(duplicates)}")
    malformed = sorted(key for key in ids if not CITEKEY.match(key))
    if malformed:
        raise SystemExit(f"malformed citekeys: {', '.join(malformed)}")
    known = {key for key, _ in GROUPS}
    ungrouped = sorted(
        entry["id"] for entry in entries if (entry.get("custom") or {}).get("group") not in known
    )
    if ungrouped:
        raise SystemExit(f"entries in an unknown group: {', '.join(ungrouped)}")
    return sorted(ids)


def write_types(ids):
    body = [
        '"""GENERATED by scripts/generate_citations.py from docs/CITATIONS.csl.json.',
        "",
        "Do not edit by hand. Run `uv run python scripts/generate_citations.py` after",
        "changing the CSL-JSON. Annotating a citekey with CitationId makes an unknown",
        "key a mypy error rather than a string that silently means nothing.",
        '"""',
        "",
        "from typing import Literal",
        "",
        "CitationId = Literal[",
    ]
    body.extend(f'    "{key}",' for key in ids)
    body.extend(["]", "", "CITATION_IDS: tuple[str, ...] = ("])
    body.extend(f'    "{key}",' for key in ids)
    body.extend([")", ""])
    with open(TYPES, "w") as fh:
        fh.write("\n".join(body))


def _names(authors):
    if not authors:
        return None
    return "; ".join(
        author["literal"]
        if author.get("literal")
        else ", ".join(part for part in (author.get("family"), author.get("given")) if part)
        for author in authors
    )


def _year(issued):
    try:
        return (issued or {})["date-parts"][0][0]
    except (KeyError, IndexError, TypeError):
        return "n.d."


def _reference(entry):
    parts = []
    who = _names(entry.get("author"))
    if who:
        parts.append(f"{who}.")
    parts.append(f"({_year(entry.get('issued'))}).")
    parts.append(f"*{entry['title']}*.")
    venue = entry.get("container-title") or entry.get("publisher")
    where = " ".join(part for part in (venue, entry.get("number")) if part)
    if where:
        parts.append(where.strip())
    locus = ": ".join(part for part in (entry.get("volume"), entry.get("page")) if part)
    if locus:
        parts.append(locus)
    return " ".join(parts).replace("  ", " ").replace(" .", ".")


def _render(entry):
    custom = entry.get("custom") or {}
    lines = [f"#### `{entry['id']}`", "", _reference(entry), ""]
    if entry.get("DOI"):
        lines.append(f"- DOI: [{entry['DOI']}](https://doi.org/{entry['DOI']})")
    elif entry.get("URL"):
        lines.append(f"- URL: <{entry['URL']}>")
    tier = f", evidence tier **{custom['evidenceTier']}**" if custom.get("evidenceTier") else ""
    label = VERIFICATION_LABEL.get(custom.get("verification"), custom.get("verification"))
    lines.append(f"- Verification: {label} | Access: {custom.get('accessLevel')}{tier}")
    if custom.get("backsClaims"):
        lines.append("- Backs:")
        lines.extend(f"  - {claim}" for claim in custom["backsClaims"])
    if custom.get("caveat"):
        lines.append(f"- **Caveat:** {custom['caveat']}")
    lines.append("")
    return "\n".join(lines)


def _tally(entries, key):
    counted = Counter(key(entry.get("custom") or {}) for entry in entries)
    return dict(sorted(counted.items()))


def _table(heading, counted, total=None):
    rows = [f"| {heading} | n |", "|---|---|"]
    rows.extend(f"| {key} | {value} |" for key, value in counted.items())
    if total is not None:
        rows.append(f"| **total** | **{total}** |")
    return "\n".join(rows)


def write_markdown(entries):
    """Regenerate the body and counts, preserving the preamble and gaps ledger."""
    with open(MARKDOWN) as fh:
        previous = fh.read()
    first_heading = f"\n## {GROUPS[0][1]}"
    if first_heading not in previous:
        raise SystemExit(f"docs/CITATIONS.md is missing the '{GROUPS[0][1]}' heading")
    preamble = previous[: previous.index(first_heading)]
    ledger_at = previous.find(LEDGER_HEADING)
    ledger = previous[ledger_at:] if ledger_at != -1 else ""

    verification = _tally(entries, lambda c: c.get("verification") or "unverified")
    access = _tally(entries, lambda c: c.get("accessLevel") or "unknown")
    tiers = _tally(entries, lambda c: c.get("evidenceTier") or "null (not applicable)")

    summary = ", ".join(f"{n} {name}" for name, n in verification.items())
    preamble = re.sub(
        r"^\d+ sources(?: \([^)]*\))?\.",
        f"{len(entries)} sources ({summary}).",
        preamble,
        count=1,
        flags=re.M,
    )
    preamble = re.sub(
        r"^### Counts\n[\s\S]*?(?=\n---\n)",
        "\n".join(
            [
                "### Counts",
                "",
                _table("Verification", verification, total=len(entries)),
                "",
                _table("Access level", access),
                "",
                _table("Evidence tier", tiers),
                "",
            ]
        ),
        preamble,
        count=1,
        flags=re.M,
    )

    body = []
    for key, heading in GROUPS:
        group = sorted(
            (e for e in entries if (e.get("custom") or {}).get("group") == key),
            key=lambda e: e["id"],
        )
        body.append(
            "\n".join(
                [f"## {heading}", "", f"{len(group)} sources.", ""] + [_render(e) for e in group]
            )
        )
    rendered = re.sub(r"\n{3,}", "\n\n", "\n".join([preamble] + body + [ledger]))
    with open(MARKDOWN, "w") as fh:
        fh.write(rendered)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated files are not already up to date",
    )
    args = parser.parse_args(argv)

    entries = load()
    ids = validate(entries)

    if args.check:
        before = {path: open(path).read() for path in (TYPES, MARKDOWN) if os.path.exists(path)}
        write_types(ids)
        write_markdown(entries)
        stale = [path for path, text in before.items() if open(path).read() != text]
        if stale or len(before) < 2:
            names = ", ".join(os.path.relpath(p, ROOT) for p in stale) or "generated files"
            print(
                f"{names} out of date; run: uv run python scripts/generate_citations.py",
                file=sys.stderr,
            )
            return 1
        print(f"{len(ids)} citekeys, generated files up to date")
        return 0

    write_types(ids)
    write_markdown(entries)
    print(f"wrote {len(ids)} citekeys to citations_generated.py and docs/CITATIONS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
